import type { LocalizedString } from '../dto/i18n.dto'
import { ALL_PERMISSIONS, VIEW_PERMISSIONS, type PermissionKey } from './permission-catalog'

export const DEFAULT_ROLE_DEFINITIONS = {
  Owner: {
    name: { ar: 'المالك', en: 'Owner' },
    description: { ar: 'صلاحية كاملة على النظام', en: 'Full system access' },
  },
  Accountant: {
    name: { ar: 'محاسب', en: 'Accountant' },
    description: { ar: 'صلاحية المحاسبة والمالية', en: 'Accounting and finance access' },
  },
  Sales: {
    name: { ar: 'موظف مبيعات', en: 'Sales' },
    description: { ar: 'إدارة المبيعات والعملاء', en: 'Sales and customer management' },
  },
  Inventory: {
    name: { ar: 'مسؤول المخزون', en: 'Inventory' },
    description: { ar: 'صلاحية المخزون والمستودعات', en: 'Inventory and warehouse access' },
  },
  Viewer: {
    name: { ar: 'مُطّلع', en: 'Viewer' },
    description: { ar: 'اطلاع فقط دون تعديل', en: 'Read-only access' },
  },
} as const satisfies Record<string, { name: LocalizedString; description: LocalizedString }>

export type DefaultRoleName = keyof typeof DEFAULT_ROLE_DEFINITIONS

export const DEFAULT_ROLE_PERMISSIONS: Record<DefaultRoleName, readonly PermissionKey[]> = {
  Owner: ALL_PERMISSIONS,
  Accountant: [
    ...VIEW_PERMISSIONS,
    'accounts.create',
    'accounts.update',
    'fiscalPeriods.create',
    'fiscalPeriods.update',
    'journals.post',
    'reconciliation.run',
    'invoices.create',
    'invoices.update',
    'invoices.post',
    'invoices.cancel',
    'payments.create',
    'payments.update',
    'payments.post',
    'payments.cancel',
    'payments.allocate',
    'expenses.create',
    'expenses.update',
    'expenses.post',
    'expenses.cancel',
    'cashboxes.create',
    'cashboxes.update',
    'bankAccounts.create',
    'bankAccounts.update',
    'parties.create',
    'parties.update',
    'files.manage',
    'ai.use',
  ],
  Sales: [
    ...VIEW_PERMISSIONS,
    'invoices.create',
    'invoices.update',
    'invoices.post',
    'payments.create',
    'parties.create',
    'parties.update',
    'files.manage',
    'ai.use',
  ],
  Inventory: [
    ...VIEW_PERMISSIONS,
    'items.create',
    'items.update',
    'items.delete',
    'itemCategories.create',
    'itemCategories.update',
    'itemCategories.delete',
    'units.create',
    'units.update',
    'units.delete',
    'brands.create',
    'brands.update',
    'brands.delete',
    'catalogEntities.create',
    'catalogEntities.update',
    'catalogEntities.delete',
    'itemCatalogEntities.create',
    'itemCatalogEntities.update',
    'itemCatalogEntities.delete',
    'itemRelations.create',
    'itemRelations.update',
    'itemRelations.delete',
    'tags.create',
    'tags.update',
    'tags.delete',
    'tagAssignments.create',
    'tagAssignments.delete',
    'warehouses.create',
    'warehouses.update',
    'warehouses.delete',
    'stockCounts.create',
    'stockCounts.post',
    'files.manage',
    'ai.use',
  ],
  Viewer: VIEW_PERMISSIONS,
}
