import type { NavGroup } from "@/base/types/navigation"

import {
  AlarmClockIcon,
  AwardIcon,
  BanknoteArrowDownIcon,
  BarChart3Icon,
  BellRingIcon,
  BookIcon,
  BriefcaseBusinessIcon,
  Building2Icon,
  CalendarCheck2Icon,
  CalendarDaysIcon,
  LayoutDashboardIcon,
  ClipboardListIcon,
  UsersIcon,
  CalendarIcon,
  CarIcon,
  ClipboardCheckIcon,
  Clock3Icon,
  ClockIcon,
  GemIcon,
  GitBranchIcon,
  HandCoinsIcon,
  ListIcon,
  ListTodoIcon,
  MegaphoneIcon,
  PackageIcon,
  PhoneCallIcon,
  PlugZapIcon,
  ReceiptIcon,
  ReceiptTextIcon,
  SettingsIcon,
  ShoppingBasketIcon,
  CircleDollarSign,
  StarIcon,
  StoreIcon,
  TimerIcon,
  UserCogIcon,
  WalletIcon,
  WrenchIcon,
  ShoppingCartIcon,
} from "lucide-react"
export const navGroups: NavGroup[] = [
  {
    items: [
      {
        title: "Dashboard",
        href: "/",
        icon: <LayoutDashboardIcon />,
      },
      {
        title: "Job Cards",
        href: "/sales/job-cards",
        icon: <ClipboardListIcon />,
      },
      {
        title: "Customer & Vehicles",
        href: "/customer-vehicles",
        icon: <UsersIcon />,
      },
      {
        title: "Reports",
        href: "/reports",
        icon: <BarChart3Icon />,
      },
    ],
  },
  {
    label: "Management",
    items: [
      {
        title: "Calendars",
        href: "/calendars",
        icon: <CalendarIcon />,
        items: [
          { title: "Work Schedule", href: "/calendar/work-schedule/list", icon: <Clock3Icon /> },
          { title: "Appointments", href: "/calendar/appointment/list", icon: <CalendarCheck2Icon /> },
        ],
      },
      {
        title: "Sales",
        href: "/sales",
        icon: <CircleDollarSign />,
        items: [
          { title: "Customers", href: "/sales/customers", icon: <UsersIcon /> },
          { title: "Vehicles", href: "/sales/vehicles", icon: <CarIcon /> },
          { title: "Inspections", href: "/sales/inspections", icon: <ClipboardCheckIcon /> },
          { title: "Estimates", href: "/sales/estimates", icon: <ReceiptTextIcon /> },
          { title: "Job Cards", href: "/sales/job-cards", icon: <ClipboardListIcon /> },
          { title: "Invoices", href: "/sales/invoice", icon: <ReceiptIcon /> },
          { title: "Payments Received", href: "/sales/payment-received", icon: <HandCoinsIcon /> },
          { title: "Credit Notes", href: "/sales/credit-notes", icon: <ReceiptTextIcon /> },
        ],
      },
      {
        title: "Purchases",
        href: "/purchases",
        icon: <ShoppingCartIcon />,
        items: [
          { title: "Vendors", href: "/purchase/vendor", icon: <StoreIcon /> },
          { title: "Expenses", href: "/purchase/expense", icon: <WalletIcon /> },
          { title: "Purchase Orders", href: "/purchase/purchase-order", icon: <ShoppingBasketIcon /> },
          { title: "Bills", href: "/purchase/bill", icon: <ReceiptIcon /> },
          { title: "Payments Made", href: "/purchase/payments-made", icon: <BanknoteArrowDownIcon /> },
          { title: "Vendor Credits", href: "/purchase/vendor-credit", icon: <ReceiptTextIcon /> },
        ],
      },
      {
        title: "CRM",
        href: "/crm",
        icon: <BriefcaseBusinessIcon />,
        items: [
          { title: "Leads", href: "/crm/leads/list", icon: <GemIcon /> },
          { title: "Calls", href: "/crm/calls-follow-up/list", icon: <PhoneCallIcon /> },
          { title: "Tasks", href: "/crm/tasks/list", icon: <ListTodoIcon /> },
        ],
      },
      {
        title: "Marketing",
        href: "/marketing",
        icon: <MegaphoneIcon />,
        items: [
          { title: "Service Reminders", href: "/marketing/service-reminder/list", icon: <AlarmClockIcon /> },
          { title: "Rating & Reviews", href: "/marketing/rating-review", icon: <StarIcon /> },
          { title: "Google Business Reviews", href: "/marketing/google-rating-review", icon: <AwardIcon /> },
        ],
      },
      {
        title: "Accountants",
        href: "/accountants",
        icon: <BookIcon />,
        items: [
          { title: "Manual Journals", href: "/accountants/manual-journal", icon: <BookIcon /> },
          { title: "Chart of Accounts", href: "/accountants/chart-of-account", icon: <GitBranchIcon /> },
        ],
      },
      {
        title: "Employees",
        href: "/productivity",
        icon: <UserCogIcon />,
        items: [
          { title: "Employees", href: "/productivity/employees", icon: <UsersIcon /> },
          { title: "Time Clocks", href: "/productivity/time-clocks", icon: <TimerIcon /> },
          { title: "Time Sheets", href: "/productivity/timesheet", icon: <ClockIcon /> },
          { title: "Payroll", href: "/productivity/payroll", icon: <WalletIcon /> },
          { title: "Payments Made", href: "/productivity/employee-payments-made", icon: <HandCoinsIcon /> },
          { title: "Shop Calendars", href: "/productivity/shop-calendars", icon: <CalendarDaysIcon /> },
          { title: "Shop Timing", href: "/productivity/shop-timings", icon: <Clock3Icon /> },
          { title: "Holidays", href: "/productivity/holidays", icon: <CalendarIcon /> },
        ],
      },
      {
        title: "Items",
        href: "/items",
        icon: <PackageIcon />,
        items: [
          { title: "Services", href: "/items/services", icon: <WrenchIcon /> },
          { title: "Parts", href: "/items/parts", icon: <WrenchIcon /> },
          { title: "Expense Item", href: "/items/expense-item", icon: <WalletIcon /> },
          { title: "Service Group", href: "/items/service-group", icon: <PackageIcon /> },
          { title: "Inspections", href: "/items/inspection", icon: <ClipboardCheckIcon /> },
          { title: "Inventory Adjustments", href: "/items/adjustment", icon: <ListIcon /> },
        ],
      },
      {
        title: "Settings",
        href: "/setting",
        icon: <SettingsIcon />,
        items: [
          { title: "Company", href: "/settings/company", icon: <Building2Icon /> },
          { title: "Shop Types", href: "/settings/shop-type", icon: <CarIcon /> },
          { title: "Tax & Rates", href: "/settings/tax-rates", icon: <ReceiptTextIcon /> },
          { title: "Configurations", href: "/settings/configurations/preferences/sales", icon: <SettingsIcon /> },
          { title: "Templates", href: "/settings/templates", icon: <ClipboardListIcon /> },
          { title: "Integrations", href: "/settings/integrations/providers", icon: <PlugZapIcon /> },
          { title: "Master", href: "/settings/master/body-type", icon: <ListIcon /> },
        ],
      },
    ],
  },
]
